name: elimu_bora
description: "A Comprehensive school management software for Ugandan Primary Schools."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  firebase_core: ^3.4.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  provider: ^6.1.2
  fl_chart: ^0.69.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
