// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3p9IKsROywL6hn28XHj405Jyp84WeyAo',
    appId: '1:290416629490:web:08f0a1fe4325807e6fa26b',
    messagingSenderId: '290416629490',
    projectId: 'elimu-bora-2fb4a',
    authDomain: 'elimu-bora-2fb4a.firebaseapp.com',
    storageBucket: 'elimu-bora-2fb4a.appspot.com',
    measurementId: 'G-ZXNYYQ1V3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxU3roMArDWvu0NwAbt0889iM8ZFoi_sg',
    appId: '1:290416629490:android:bdcea163ec3564b16fa26b',
    messagingSenderId: '290416629490',
    projectId: 'elimu-bora-2fb4a',
    storageBucket: 'elimu-bora-2fb4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATxld4TD-aljGHbnt89UF2Eg8OFLLyFOM',
    appId: '1:290416629490:ios:1e9ee4f8547ffb346fa26b',
    messagingSenderId: '290416629490',
    projectId: 'elimu-bora-2fb4a',
    storageBucket: 'elimu-bora-2fb4a.appspot.com',
    iosBundleId: 'com.example.elimuBora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATxld4TD-aljGHbnt89UF2Eg8OFLLyFOM',
    appId: '1:290416629490:ios:1e9ee4f8547ffb346fa26b',
    messagingSenderId: '290416629490',
    projectId: 'elimu-bora-2fb4a',
    storageBucket: 'elimu-bora-2fb4a.appspot.com',
    iosBundleId: 'com.example.elimuBora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3p9IKsROywL6hn28XHj405Jyp84WeyAo',
    appId: '1:290416629490:web:7c82a7159640c0d16fa26b',
    messagingSenderId: '290416629490',
    projectId: 'elimu-bora-2fb4a',
    authDomain: 'elimu-bora-2fb4a.firebaseapp.com',
    storageBucket: 'elimu-bora-2fb4a.appspot.com',
    measurementId: 'G-QPVJMJ8WSQ',
  );

}